install-wasi-target:
    rustup target add wasm32-wasip2

build mode="debug": install-wasi-target 
    cargo component build {{ if mode == "release" { "--release" } else { "" } }}

test: build
    echo "Testing HTML to Markdown component..."
    # wasmtime run target/wasm32-wasip1/debug/html_to_markdown_rs.wasm